# Site settings
title: "Application State Binder"
description: "This is the project page of my app-state-binder-js library, which reveals the application state in the hash of the url."
url: "http://stefandollase.github.io" # the base hostname & protocol for your site
baseurl: "/app-state-binder-js" # the subpath of your site, e.g. /blog/

# About the author
author_fullname: "Stefan Dollase"
author_address: [ "Harscampstraße 22", "52062 Aachen" ]
email: "app-state-binder-js@stefandollase.de"
github_username: "stefandollase"

# Disqus settings
#disqus_shortname: ""
#disqus_identifier_prefix: ""

# Build settings
markdown: kramdown
